Repository envoyproxy/nighthawk, pull requests merged in 2020-09, with the labels that each got.

#499 Fix (enable) integration test coverage in CI
  .circleci/config.yml
Labels: waiting-for-review

#477 Echo back and track origin request-receipt timing deltas
  api/server/response_options.proto
  include/nighthawk/common/BUILD
  include/nighthawk/common/stopwatch.h
  source/client/benchmark_client_impl.cc
  source/client/benchmark_client_impl.h
  source/client/factories_impl.cc
  source/client/stream_decoder.cc
  source/client/stream_decoder.h
  source/common/BUILD
  source/common/thread_safe_monotonic_time_stopwatch.cc
  source/common/thread_safe_monotonic_time_stopwatch.h
  source/server/BUILD
  source/server/http_time_tracking_filter.cc
  source/server/http_time_tracking_filter.h
  source/server/http_time_tracking_filter_config.cc
  test/BUILD
  test/benchmark_http_client_test.cc
  test/server/BUILD
  test/server/http_time_tracking_filter_integration_test.cc
  test/stopwatch_test.cc
  test/stream_decoder_test.cc
Labels: waiting-for-review

#503 Fix uri parsing bug & add some unit test coverage for client.cc
  ci/do_ci.sh
  source/common/uri_impl.cc
  test/client_test.cc
  test/integration/test_integration_basics.py
  test/utility_test.cc
Labels: waiting-for-review

#506 Set explicit --jobs value in ci/do_ci.sh only when running on CircleCI
  ci/do_ci.sh
Labels: waiting-for-review

#504 Update Envoy to f1c0031819ddc7b8a9f6352ad6722f4abf8ab664
  bazel/repositories.bzl
Labels: waiting-for-review

#493 Adaptive Load library for calling Nighthawk Service
  api/client/BUILD
  include/nighthawk/common/BUILD
  include/nighthawk/common/nighthawk_service_client.h
  source/common/BUILD
  source/common/nighthawk_service_client_impl.cc
  source/common/nighthawk_service_client_impl.h
  test/common/BUILD
  test/common/nighthawk_service_client_test.cc
  tools/check_format.sh
Labels: waiting-for-review

#511 Avoid high frequency logging
  source/client/benchmark_client_impl.cc
  source/client/stream_decoder.cc
  source/common/statistic_impl.cc
Labels: waiting-for-review

#516 Allow 0s as a value to the jitter-uniform option.
  api/client/options.proto
  source/client/options_impl.cc
  source/client/output_formatter_impl.cc
  test/options_test.cc
  test/output_formatter_test.cc
Labels: waiting-for-review

#494 Allow ENVOY_LOG to log messages in user-specified logging level and format
  source/client/service_impl.h
  test/service_test.cc
Labels: waiting-for-review

#500 Finalize emission and tracking of latencies in response headers
  BUILD
  README.md
  api/client/options.proto
  include/nighthawk/client/options.h
  source/client/benchmark_client_impl.cc
  source/client/benchmark_client_impl.h
  source/client/factories_impl.cc
  source/client/options_impl.cc
  source/client/options_impl.h
  source/client/stream_decoder.cc
  source/client/stream_decoder.h
  source/server/http_time_tracking_filter.h
  test/benchmark_http_client_test.cc
  test/factories_test.cc
  test/integration/BUILD
  test/integration/configurations/nighthawk_track_timings.yaml
  test/integration/test_integration_basics.py
  test/mocks/client/mock_options.h
  test/options_test.cc
  test/stream_decoder_test.cc
Labels: waiting-for-review

#510 Build an image containing the benchmark infrastructure
  ci/docker/Dockerfile-nighthawk-benchmark
  ci/docker/benchmark_build.sh
Labels: waiting-for-changes

#521 Lower integration test coverage threshold
  ci/do_ci.sh
Labels: waiting-for-review

#519 Update Envoy to 5187c347f878e322ca9c78807446189c1335fb5c
  .bazelrc
  .circleci/config.yml
  bazel/repositories.bzl
  source/client/benchmark_client_impl.cc
Labels: waiting-for-review

#495 Adaptive Load metrics evaluator library
  include/nighthawk/adaptive_load/BUILD
  include/nighthawk/adaptive_load/metrics_evaluator.h
  source/adaptive_load/BUILD
  source/adaptive_load/metrics_evaluator_impl.cc
  source/adaptive_load/metrics_evaluator_impl.h
  test/adaptive_load/BUILD
  test/adaptive_load/metrics_evaluator_test.cc
Labels: waiting-for-review

#518 Add FilterConfigurationBase
  source/server/http_filter_config_base.cc
  source/server/http_filter_config_base.h
Labels: waiting-for-review

#508 Adaptive load session spec proto helpers
  include/nighthawk/adaptive_load/BUILD
  include/nighthawk/adaptive_load/session_spec_proto_helper.h
  source/adaptive_load/BUILD
  source/adaptive_load/session_spec_proto_helper_impl.cc
  source/adaptive_load/session_spec_proto_helper_impl.h
  test/adaptive_load/BUILD
  test/adaptive_load/fake_plugins/fake_metrics_plugin/fake_metrics_plugin.cc
  test/adaptive_load/fake_plugins/fake_metrics_plugin/fake_metrics_plugin.h
  test/adaptive_load/fake_plugins/fake_metrics_plugin/fake_metrics_plugin_test.cc
  test/adaptive_load/session_spec_proto_helper_test.cc
Labels: waiting-for-review

#524 Add dubious90 to the list of owners.
  CONTRIBUTING.md
  MAINTAINERS.md
  OWNERS.md
Labels: waiting-for-review

#523 Eliminate configuration references to Envoy's fault filter.
  ci/docker/default-config.yaml
  test/integration/configurations/nighthawk_http_origin.yaml
Labels: waiting-for-review

#527 Adaptive load helper interface cleanup and dep/header cleanup
  include/nighthawk/adaptive_load/BUILD
  include/nighthawk/adaptive_load/metrics_evaluator.h
  include/nighthawk/adaptive_load/session_spec_proto_helper.h
  include/nighthawk/common/nighthawk_service_client.h
  source/adaptive_load/session_spec_proto_helper_impl.cc
  source/adaptive_load/session_spec_proto_helper_impl.h
  source/common/nighthawk_service_client_impl.cc
  source/common/nighthawk_service_client_impl.h
Labels: waiting-for-review

#530 Source/server/configuration.cc/h: const options arg.
  source/server/configuration.cc
  source/server/configuration.h
Labels: waiting-for-review

#532 Enhance end-to-end test for POST requests with an entity body.
  test/integration/configurations/nighthawk_http_origin.yaml
  test/integration/test_integration_basics.py
Labels: waiting-for-review

#529 Adaptive load helper mocks
  test/mocks/adaptive_load/BUILD
  test/mocks/adaptive_load/mock_metrics_evaluator.cc
  test/mocks/adaptive_load/mock_metrics_evaluator.h
  test/mocks/adaptive_load/mock_session_spec_proto_helper.cc
  test/mocks/adaptive_load/mock_session_spec_proto_helper.h
  test/mocks/common/BUILD
  test/mocks/common/mock_nighthawk_service_client.cc
  test/mocks/common/mock_nighthawk_service_client.h
Labels: waiting-for-review

#536 Add opt_build option to ci/do_ci.sh.
  ci/do_ci.sh
Labels: waiting-for-review

#537 Test benchmark docker image build in CI
  ci/do_ci.sh
Labels: waiting-for-review

#517 Add HttpFilterIntegrationTestBase
  test/server/BUILD
  test/server/http_filter_integration_test_base.cc
  test/server/http_filter_integration_test_base.h
Labels: waiting-for-review

#534 Add experimental "pedantic" fortio output formatter.
  README.md
  api/client/options.proto
  source/client/output_formatter_impl.cc
  source/client/output_formatter_impl.h
  test/BUILD
  test/output_formatter_test.cc
  test/test_data/output_formatter.medium.fortio-noquirks.gold
Labels: waiting-for-review

#544 Avoid crash with the experimental fortio pedantic formatter
  source/client/factories_impl.cc
  test/output_transform_main_test.cc
Labels: waiting-for-review

#545 Update Envoy & HdrHistogram_c
  .bazelrc
  bazel/repositories.bzl
  source/server/README.md
Labels: waiting-for-review

#540 Switch dynamic delay and time-tracking to use FilterConfigurationBase.
  source/server/BUILD
  source/server/http_dynamic_delay_filter.cc
  source/server/http_dynamic_delay_filter.h
  source/server/http_filter_config_base.cc
  source/server/http_filter_config_base.h
  source/server/http_time_tracking_filter.cc
  source/server/http_time_tracking_filter.h
Labels: waiting-for-review

#548 Implement RemoteProcessImpl in terms of PerformNighthawkBenchmark()
  source/client/BUILD
  source/client/remote_process_impl.cc
  source/client/remote_process_impl.h
Labels: waiting-for-review

#535 Adaptive Load Controller main loop
  include/nighthawk/adaptive_load/adaptive_load_controller.h
  source/adaptive_load/BUILD
  source/adaptive_load/adaptive_load_controller_impl.cc
  source/adaptive_load/adaptive_load_controller_impl.h
  test/adaptive_load/BUILD
  test/adaptive_load/adaptive_load_controller_test.cc
  test/adaptive_load/fake_plugins/fake_step_controller/fake_step_controller.cc
  test/adaptive_load/fake_plugins/fake_step_controller/fake_step_controller.h
  test/adaptive_load/fake_plugins/fake_step_controller/fake_step_controller_test.cc
Labels: waiting-for-review

#533 Add generic c++ integration test for uniform extension behavior.
  test/server/BUILD
  test/server/http_filter_base_test.cc
Labels: waiting-for-review

#541 Use shared test facilities for time-tracking and dynamic-delay
  test/server/http_dynamic_delay_filter_integration_test.cc
  test/server/http_time_tracking_filter_integration_test.cc
Labels: waiting-for-review

#552 Fix jitter behavior for large values.
  source/common/rate_limiter_impl.cc
  source/common/rate_limiter_impl.h
  test/rate_limiter_test.cc
Labels: bug, waiting-for-review

#554 Update Envoy to 5a87f1e59b42ad546698d389f6ccac9406534e17
  bazel/repositories.bzl
Labels: waiting-for-review

#556 Fix import in Zipkin integration tests.
  test/integration/test_integration_zipkin.py
Labels: waiting-for-review

#549 Use system time for scheduling.
  include/nighthawk/common/factories.h
  source/client/client_worker_impl.cc
  source/client/client_worker_impl.h
  source/client/factories_impl.cc
  source/client/factories_impl.h
  source/client/process_impl.cc
  source/common/cached_time_source_impl.h
  source/common/rate_limiter_impl.cc
  source/common/rate_limiter_impl.h
  source/common/sequencer_impl.cc
  source/common/sequencer_impl.h
  source/common/termination_predicate_impl.cc
  source/common/termination_predicate_impl.h
  test/client_worker_test.cc
  test/factories_test.cc
  test/mocks/common/mock_sequencer_factory.h
  test/mocks/common/mock_termination_predicate_factory.h
  test/rate_limiter_test.cc
  test/sequencer_test.cc
  test/termination_predicate_test.cc
Labels: waiting-for-review
