Repository envoyproxy/nighthawk, pull requests merged in 2020-01, with the labels that each got.

#246 Add overview.md
  docs/root/draft-high-level-diagram.png
  docs/root/overview.md
  docs/root/terminology.md
Labels: P0, waiting-for-review

#198 Add "fair" HTTP/1 connection reuse strategy
  README.md
  api/client/options.proto
  include/nighthawk/client/options.h
  source/client/benchmark_client_impl.cc
  source/client/benchmark_client_impl.h
  source/client/options_impl.cc
  source/client/options_impl.h
  source/client/process_impl.cc
  test/integration/test_connection_management.py
  test/mocks.h
  test/options_test.cc
Labels: P1, waiting-for-review

#218 Linear ramping and probabilistic ramping
  include/nighthawk/common/rate_limiter.h
  source/common/BUILD
  source/common/rate_limiter_impl.cc
  source/common/rate_limiter_impl.h
  test/rate_limiter_test.cc
Labels: P3, waiting-for-review

#254 Update MAINTAINERS.md: mention pre-merge commit message cleanup
  MAINTAINERS.md
Labels: P0, waiting-for-review

#253 Push to envoyproxy/nighthawk-dev:latest
  ci/do_ci.sh
  ci/docker/docker_push.sh
Labels: P0, waiting-for-review

#240 Add --transport-socket command line option
  README.md
  api/client/options.proto
  include/nighthawk/client/options.h
  source/client/options_impl.cc
  source/client/options_impl.h
  source/client/process_impl.cc
  test/integration/integration_test_fixtures.py
  test/integration/test_integration_basics.py
  test/mocks.h
  test/options_test.cc
Labels: waiting-for-review

#255 Labels option
  README.md
  api/client/options.proto
  api/client/transform/fortio.proto
  include/nighthawk/client/options.h
  source/client/options_impl.cc
  source/client/options_impl.h
  source/client/output_formatter_impl.cc
  test/mocks.h
  test/options_test.cc
  test/test_data/output_formatter.json.gold
  test/test_data/output_formatter.medium.proto.gold
  test/test_data/output_formatter.yaml.gold
Labels: P0, waiting-for-review

#264 Temporary fix for TimingVerificationTest determinism
  test/rate_limiter_test.cc
Labels: P0, waiting-for-review

#252 Spread generated traffic across multiple backends
  README.md
  api/client/options.proto
  include/nighthawk/client/options.h
  source/client/factories_impl.cc
  source/client/options_impl.cc
  source/client/options_impl.h
  source/client/process_impl.cc
  source/client/process_impl.h
  source/common/utility.cc
  source/common/utility.h
  test/client/utility.cc
  test/client_test.cc
  test/factories_test.cc
  test/integration/integration_test_fixtures.py
  test/integration/test_integration_basics.py
  test/mocks.h
  test/options_test.cc
Labels: P0, waiting-for-review

#200 Experimental multi-connection H2 pool
  README.md
  api/client/options.proto
  include/nighthawk/client/options.h
  source/client/BUILD
  source/client/benchmark_client_impl.cc
  source/client/benchmark_client_impl.h
  source/client/options_impl.cc
  source/client/options_impl.h
  source/client/process_impl.cc
  test/integration/test_integration_basics.py
  test/mocks.h
  test/options_test.cc
  test/run_nighthawk_bazel_coverage.sh
Labels: P1, waiting-for-review

#266 Remove TODO(#263) code comment
  test/rate_limiter_test.cc
Labels: waiting-for-review

#261 Update Envoy
  .bazelrc
  .circleci/config.yml
  api/client/BUILD
  api/client/options.proto
  bazel/repositories.bzl
  include/nighthawk/client/options.h
  source/client/factories_impl.cc
  source/client/options_impl.cc
  source/client/options_impl.h
  source/client/process_impl.cc
  source/client/process_impl.h
  source/server/README.md
  source/server/http_test_server_filter_config.cc
  test/mocks.h
  test/options_test.cc
Labels: P0, waiting-for-review

#270 HdrHistogram: 0.9.11 -> 0.9.12
  bazel/repositories.bzl
Labels: P2, waiting-for-review

#275 CLI: Avoid double angle brackets in docs
  README.md
  source/client/options_impl.cc
Labels: P3, bug

#250 nighthawk_client remote execution option
  README.md
  api/client/options.proto
  include/nighthawk/client/options.h
  include/nighthawk/client/output_collector.h
  source/client/BUILD
  source/client/client.cc
  source/client/options_impl.cc
  source/client/options_impl.h
  source/client/output_collector_impl.h
  source/client/remote_process_impl.cc
  source/client/remote_process_impl.h
  test/integration/BUILD
  test/integration/nighthawk_grpc_service.py
  test/integration/test_remote_execution.py
  test/mocks.h
Labels: P1, waiting-for-review

#251 Add zipf distributing ratelimiter
  source/common/rate_limiter_impl.cc
  source/common/rate_limiter_impl.h
  test/rate_limiter_test.cc
Labels: P3, waiting-for-review

#226 Fortio output: add missing fields & correct some of the output fields
  api/client/output.proto
  api/client/transform/fortio.proto
  source/client/BUILD
  source/client/options_impl.cc
  source/client/output_collector_impl.cc
  source/client/output_formatter_impl.cc
  source/client/output_formatter_impl.h
  source/client/output_transform_main.cc
  source/client/service_main.cc
  source/common/BUILD
  source/common/version_info.cc
  source/common/version_info.h
  test/output_formatter_test.cc
  test/test_data/output_formatter.json.gold
  test/test_data/output_formatter.medium.fortio.gold
  test/test_data/output_formatter.medium.proto.gold
  test/test_data/output_formatter.yaml.gold
Labels: P0, waiting-for-review

#279 CI: Decrease parlallelism in asan test job
  ci/do_ci.sh
Labels: P0

#137 RemoteHeaderSource & stub grpc service HeaderStreamRequest
  README.md
  api/request_source/BUILD
  include/nighthawk/client/factories.h
  include/nighthawk/client/options.h
  include/nighthawk/common/BUILD
  include/nighthawk/common/request_source.h
  include/nighthawk/common/request_stream_grpc_client.h
  source/client/BUILD
  source/client/benchmark_client_impl.cc
  source/client/client_worker_impl.cc
  source/client/factories_impl.cc
  source/client/factories_impl.h
  source/client/options_impl.cc
  source/client/options_impl.h
  source/client/process_impl.cc
  source/client/process_impl.h
  source/client/service_impl.cc
  source/client/service_impl.h
  source/client/service_main.cc
  source/client/service_main.h
  source/common/BUILD
  source/common/request_source_impl.cc
  source/common/request_source_impl.h
  source/common/request_stream_grpc_client_impl.cc
  source/common/request_stream_grpc_client_impl.h
  source/common/uri_impl.cc
  source/common/uri_impl.h
  source/common/utility.cc
  test/BUILD
  test/client_worker_test.cc
  test/factories_test.cc
  test/integration/BUILD
  test/integration/integration_test_fixtures.py
  test/integration/nighthawk_grpc_service.py
  test/integration/test_grpc_service.py
  test/mocks.h
  test/options_test.cc
  test/request_stream_grpc_client_test.cc
  test/utility_test.cc
Labels: P2, waiting-for-review

#232 Add RELEASE_PROCEDURE.md
  RELEASE_PROCEDURE.md
Labels: P2, waiting-for-review

#281 rate-limiting: Add ScheduledStartingRateLimiter
  source/common/rate_limiter_impl.cc
  source/common/rate_limiter_impl.h
  test/rate_limiter_test.cc
Labels: P2, waiting-for-review

#276 style: rename thread_local_counter_values
  include/nighthawk/client/client_worker.h
  source/client/client_worker_impl.cc
  source/client/client_worker_impl.h
  source/client/process_impl.cc
Labels: P3, waiting-for-review

#219 Introduce Phases
  include/nighthawk/client/benchmark_client.h
  include/nighthawk/client/client_worker.h
  include/nighthawk/client/factories.h
  include/nighthawk/common/BUILD
  include/nighthawk/common/phase.h
  include/nighthawk/common/termination_predicate.h
  source/client/benchmark_client_impl.cc
  source/client/benchmark_client_impl.h
  source/client/client_worker_impl.cc
  source/client/client_worker_impl.h
  source/client/factories_impl.cc
  source/client/factories_impl.h
  source/client/process_impl.cc
  source/common/BUILD
  source/common/phase_impl.cc
  source/common/phase_impl.h
  source/common/sequencer_impl.cc
  source/common/sequencer_impl.h
  source/common/termination_predicate_impl.cc
  source/common/termination_predicate_impl.h
  test/benchmark_http_client_test.cc
  test/client_worker_test.cc
  test/factories_test.cc
  test/integration/test_integration_basics.py
  test/mocks.h
  test/sequencer_test.cc
  test/termination_predicate_test.cc
Labels: P2, waiting-for-review

#274 Facilitate SNI
  source/client/BUILD
  source/client/options_impl.cc
  source/client/process_impl.cc
  source/client/sni_utility.cc
  source/client/sni_utility.h
  test/BUILD
  test/integration/BUILD
  test/integration/configurations/sni_origin.yaml
  test/integration/integration_test_fixtures.py
  test/integration/test_integration_basics.py
  test/options_test.cc
  test/process_test.cc
  test/sni_utility_test.cc
Labels: P3, enhancement, waiting-for-review

#265 Add tracking of response body-size and header-size
  api/client/output.proto
  api/client/transform/fortio.proto
  include/nighthawk/common/statistic.h
  source/client/benchmark_client_impl.cc
  source/client/benchmark_client_impl.h
  source/client/factories_impl.cc
  source/client/output_collector_impl.cc
  source/client/output_formatter_impl.cc
  source/client/output_formatter_impl.h
  source/client/process_impl.cc
  source/client/process_impl.h
  source/client/stream_decoder.cc
  source/client/stream_decoder.h
  source/common/BUILD
  source/common/statistic_impl.cc
  source/common/statistic_impl.h
  source/common/version_info.h
  test/benchmark_http_client_test.cc
  test/integration/test_integration_basics.py
  test/output_formatter_test.cc
  test/statistic_test.cc
  test/stream_decoder_test.cc
  test/test_data/hdr_proto_json.gold
  test/test_data/output_formatter.dotted.gold
  test/test_data/output_formatter.json.gold
  test/test_data/output_formatter.medium.fortio.gold
  test/test_data/output_formatter.medium.proto.gold
  test/test_data/output_formatter.txt.gold
  test/test_data/output_formatter.yaml.gold
Labels: P0, waiting-for-review

#285 Re-introduce phases
  include/nighthawk/client/benchmark_client.h
  include/nighthawk/client/client_worker.h
  include/nighthawk/client/factories.h
  include/nighthawk/common/BUILD
  include/nighthawk/common/phase.h
  include/nighthawk/common/termination_predicate.h
  source/client/benchmark_client_impl.cc
  source/client/benchmark_client_impl.h
  source/client/client_worker_impl.cc
  source/client/client_worker_impl.h
  source/client/factories_impl.cc
  source/client/factories_impl.h
  source/client/process_impl.cc
  source/common/BUILD
  source/common/phase_impl.cc
  source/common/phase_impl.h
  source/common/rate_limiter_impl.cc
  source/common/rate_limiter_impl.h
  source/common/sequencer_impl.cc
  source/common/sequencer_impl.h
  source/common/termination_predicate_impl.h
  test/benchmark_http_client_test.cc
  test/client_worker_test.cc
  test/factories_test.cc
  test/integration/integration_test_fixtures.py
  test/integration/test_integration_basics.py
  test/mocks.h
  test/rate_limiter_test.cc
  test/run_nighthawk_bazel_coverage.sh
  test/sequencer_test.cc
  test/termination_predicate_test.cc
Labels: P0, waiting-for-review

#293 Introduce cached time source
  source/client/client_worker_impl.cc
  source/client/client_worker_impl.h
  source/common/BUILD
  source/common/cached_time_source_impl.h
  source/common/sequencer_impl.cc
  test/sequencer_test.cc
Labels: P2, waiting-for-review

#295 Simple warmup: default to opting out
  README.md
  api/client/options.proto
  docs/root/version_history.md
  include/nighthawk/client/options.h
  source/client/client_worker_impl.cc
  source/client/client_worker_impl.h
  source/client/options_impl.cc
  source/client/options_impl.h
  source/client/process_impl.cc
  test/client_test.cc
  test/client_worker_test.cc
  test/integration/test_connection_management.py
  test/integration/test_integration_basics.py
  test/mocks.h
  test/options_test.cc
Labels: P0, waiting-for-review

#297 Minor changes to fix MAC builds.
  source/client/options_impl.cc
  source/common/platform_util_impl.h
Labels: waiting-for-review
