Repository envoyproxy/nighthawk, pull requests merged in 2020-06, with the labels that each got.

#341 support non-default buildifier/buildozer paths
  ci/do_ci.sh
Labels: waiting-for-review

#343 Update Envoy to ff40a02a838d123f4bf018858c61c983e1c5cce9
  bazel/repositories.bzl
  source/server/README.md
Labels: P1, waiting-for-review

#338 Add echo_request_headers to the test server filter ResponseOptions.
  api/server/response_options.proto
  source/server/README.md
  source/server/http_test_server_filter.cc
  source/server/http_test_server_filter.h
  test/server/http_test_server_filter_integration_test.cc
Labels: waiting-for-changes

#354 Cli percentile column fit
  source/client/output_formatter_impl.cc
  test/BUILD
  test/output_formatter_test.cc
  test/test_data/percentile-column-overflow.json
  test/test_data/percentile-column-overflow.txt.gold
Labels: P1, waiting-for-review

#359 Update Envoy to b612236bcd8ef3cd14d904c21348888a6755d5d6
  bazel/repositories.bzl
  source/server/README.md
Labels: P1, waiting-for-review

#357 integration-tests: tweaks to stabilize sanitizer runs
  test/integration/nighthawk_grpc_service.py
  test/integration/nighthawk_test_server.py
  test/integration/test_connection_management.py
  test/integration/test_grpc_service.py
  test/integration/test_integration_basics.py
  test/integration/test_remote_execution.py
Labels: P1, waiting-for-review

#282 Extract SignalHandler class for re-use
  source/client/service_main.cc
  source/client/service_main.h
  source/common/BUILD
  source/common/signal_handler.cc
  source/common/signal_handler.h
Labels: P3, waiting-for-review

#366 Add "no-duration" to facilitate infinite load generation
  README.md
  api/client/options.proto
  include/nighthawk/client/options.h
  source/client/factories_impl.cc
  source/client/options_impl.cc
  source/client/options_impl.h
  source/client/process_impl.cc
  source/common/termination_predicate_impl.cc
  source/common/termination_predicate_impl.h
  test/mocks/client/mock_options.h
  test/options_test.cc
  test/run_nighthawk_bazel_coverage.sh
Labels: P1, waiting-for-changes

#363 gRPC service logging bugfix
  source/client/process_impl.cc
  source/client/process_impl.h
  source/client/service_impl.cc
  source/client/service_impl.h
  test/integration/nighthawk_grpc_service.py
  test/integration/test_remote_execution.py
Labels: P1, waiting-for-review

#365 Avoid log warning for tls_context if the user didn't set it
  source/client/options_impl.cc
Labels: P1, waiting-for-review

#358 Coverage testing and docker flow fixes
  .bazelrc
  ci/envoy_build_sha.sh
  test/BUILD
  test/integration/BUILD
  test/integration/test_grpc_service.py
  test/integration/test_integration_basics.py
  test/integration/test_output_transform.py
  test/integration/utility.py
  test/rate_limiter_test.cc
  test/run_nighthawk_bazel_coverage.sh
  test/statistic_test.cc
Labels: P1, waiting-for-review

#373 TerminationPredicateTest: explicitly order std::move/get reference
  test/termination_predicate_test.cc
Labels: P1, waiting-for-review

#368 Fix benchmark_http_client_test.cc and add test cases.
  test/benchmark_http_client_test.cc
Labels: P2, waiting-for-review

#376 Update Envoy to 12b3d2c2ffa582507e5d6dd34632b2b990f1b195
  .bazelrc
  .circleci/config.yml
  .clang-tidy
  bazel/repositories.bzl
  source/client/factories_impl.cc
  source/client/service_impl.cc
  source/client/stream_decoder.cc
  source/common/rate_limiter_impl.cc
  source/common/request_stream_grpc_client_impl.cc
  test/benchmark_http_client_test.cc
  test/run_nighthawk_bazel_coverage.sh
  test/server/http_test_server_filter_integration_test.cc
  test/stream_decoder_test.cc
Labels: P1, waiting-for-review

#367 CLI - cancel execution upon signal reception
  include/nighthawk/client/client_worker.h
  include/nighthawk/client/process.h
  source/client/client.cc
  source/client/client_worker_impl.cc
  source/client/client_worker_impl.h
  source/client/factories_impl.cc
  source/client/process_impl.cc
  source/client/process_impl.h
  source/client/remote_process_impl.cc
  source/client/remote_process_impl.h
  source/common/termination_predicate_impl.cc
  source/common/termination_predicate_impl.h
  test/integration/test_integration_basics.py
  test/process_test.cc
Labels: P1, waiting-for-review

#384 Cover --no-duration and restore the CI coverage percentage threshold
  test/integration/test_integration_basics.py
  test/options_test.cc
  test/run_nighthawk_bazel_coverage.sh
Labels: P1, waiting-for-review

#337 Dockerized benchmarking framework
  .circleci/config.yml
  WORKSPACE
  benchmarks/.gitignore
  benchmarks/BUILD
  benchmarks/README.md
  benchmarks/benchmark-visual-example.png
  benchmarks/benchmarks.py
  benchmarks/configurations/envoy_proxy.yaml
  benchmarks/docker/Dockerfile-benchmark
  benchmarks/docker/docker_build.sh
  benchmarks/envoy_proxy.py
  benchmarks/run_benchmark.sh
  benchmarks/test/README.md
  benchmarks/test/templates/simple_plot.html
  benchmarks/test/test_discovery.py
  benchmarks/test_benchmark.py
  ci/do_ci.sh
  requirements.txt
  test/integration/BUILD
  test/integration/configurations/nighthawk_http_origin.yaml
  test/integration/configurations/nighthawk_https_origin.yaml
  test/integration/configurations/sni_origin.yaml
  test/integration/integration_test_fixtures.py
  test/integration/nighthawk_grpc_service.py
  test/integration/nighthawk_test_server.py
  test/integration/test_connection_management.py
  test/integration/test_grpc_service.py
  test/integration/test_integration_basics.py
  test/integration/test_integration_zipkin.py
  test/integration/test_remote_execution.py
  tools/format_python_tools.sh
  tools/requirements.txt
Labels: P1, waiting-for-review

#386 Update Envoy to 5c553261d14730af5a2c290c4b3687ae667a65db
  bazel/repositories.bzl
  source/client/benchmark_client_impl.cc
  source/client/process_impl.cc
Labels: P1, waiting-for-review
