Repository envoyproxy/nighthawk, pull requests merged in 2020-07, with the labels that each got.

#394 Update Envoy to f6b86a58b264b46a57d71a9b3b0989b2969df408
  .bazelrc
  .circleci/config.yml
  bazel/repositories.bzl
  source/client/benchmark_client_impl.cc
Labels: P1, waiting-for-review

#397 CI: Test that we can produce artifacts with gcc
  .circleci/config.yml
  .gitignore
  ci/do_ci.sh
  tools/valgrind-suppressions.txt
  tools/valgrind-tests.sh
  tools/valgrind.sh
Labels: waiting-for-review

#402 Update HdrHistogram_c to 0.11.0
  bazel/repositories.bzl
Labels: waiting-for-review

#391 Add new NH statistic class CircllhistStatistic and SinkableCircllhist…
  source/common/BUILD
  source/common/statistic_impl.cc
  source/common/statistic_impl.h
  test/BUILD
  test/run_nighthawk_bazel_coverage.sh
  test/statistic_test.cc
  test/test_data/circllhist_proto_json.gold
Labels: waiting-for-review

#390 Test server dynamic delay
  BUILD
  api/server/response_options.proto
  source/server/BUILD
  source/server/README.md
  source/server/configuration.cc
  source/server/configuration.h
  source/server/http_dynamic_delay_filter.cc
  source/server/http_dynamic_delay_filter.h
  source/server/http_dynamic_delay_filter_config.cc
  source/server/http_test_server_filter.cc
  source/server/http_test_server_filter.h
  source/server/well_known_headers.h
  test/client_test.cc
  test/integration/configurations/nighthawk_http_origin.yaml
  test/server/BUILD
  test/server/http_dynamic_delay_filter_integration_test.cc
  test/server/http_test_server_filter_integration_test.cc
  tools/check_envoy_includes.py
Labels: waiting-for-review

#403 Add missing dependencies to run tools/gen_compilation_database.py
  requirements.txt
Labels: waiting-for-review

#401 Update Envoy to 7abb0e0bbed4f6b6304403b93762614ad385f80d
  .bazelrc
  bazel/repositories.bzl
  ci/do_ci.sh
  source/client/BUILD
  source/client/benchmark_client_impl.h
  source/client/process_impl.h
  source/client/stream_decoder.h
  source/server/README.md
  test/BUILD
  test/benchmark_http_client_test.cc
  test/client_worker_test.cc
  test/stream_decoder_test.cc
  test/worker_test.cc
Labels: waiting-for-review

#395 Stricter and more checks for python code
  benchmarks/envoy_proxy.py
  benchmarks/test/test_discovery.py
  test/integration/BUILD
  test/integration/asserts.py
  test/integration/common.py
  test/integration/integration_test.py
  test/integration/integration_test_fixtures.py
  test/integration/nighthawk_grpc_service.py
  test/integration/nighthawk_test_server.py
  test/integration/test_connection_management.py
  test/integration/test_grpc_service.py
  test/integration/test_integration_basics.py
  test/integration/test_integration_zipkin.py
  test/integration/test_output_transform.py
  test/integration/test_remote_execution.py
  test/integration/utility.py
  tools/check_envoy_includes.py
  tools/format_python_tools.py
  tools/format_python_tools.sh
  tools/gen_compilation_database.py
  tools/requirements.txt
  tools/update_cli_readme_documentation.py
Labels: P1, enhancement, tech-debt, waiting-for-review

#413 test: Declare python version for benchmark sources
  benchmarks/BUILD
Labels: waiting-for-review

#412 Update Envoy to 13da8f415c372e7fde3b0105f58f57348e84acb5
  .bazelrc
  .bazelversion
  .circleci/config.yml
  .clang-tidy
  bazel/repositories.bzl
  source/client/service_impl.cc
Labels: waiting-for-review

#415 CI: lower test_gcc parallellism.
  ci/do_ci.sh
Labels: waiting-for-review

#411 Add a macos specific tweak to .bazelrc to fix the OSX build
  .bazelrc
Labels: waiting-for-review

#418 Add CLI flags "stats-sinks" and "stats-flush-interval" to support configure stat sinks in NH
  README.md
  api/client/BUILD
  api/client/options.proto
  include/nighthawk/client/BUILD
  include/nighthawk/client/options.h
  source/client/options_impl.cc
  source/client/options_impl.h
  test/mocks/client/mock_options.h
  test/options_test.cc
  test/test_data/output_formatter.json.gold
  test/test_data/output_formatter.yaml.gold
Labels: waiting-for-review

#381 Add stats to record latency metrics for each response code in NH
  docs/root/statistics.md
  include/nighthawk/client/factories.h
  source/client/benchmark_client_impl.cc
  source/client/benchmark_client_impl.h
  source/client/client_worker_impl.cc
  source/client/factories_impl.cc
  source/client/factories_impl.h
  source/client/stream_decoder.cc
  source/client/stream_decoder.h
  source/common/statistic_impl.cc
  source/common/statistic_impl.h
  test/benchmark_http_client_test.cc
  test/client_worker_test.cc
  test/factories_test.cc
  test/integration/test_integration_basics.py
  test/mocks/client/mock_benchmark_client_factory.h
  test/statistic_test.cc
  test/stream_decoder_test.cc
Labels: P1, waiting-for-review

#398 Adaptive Load Controller protos
  api/adaptive_load/BUILD
  api/adaptive_load/adaptive_load.proto
  api/adaptive_load/benchmark_result.proto
  api/adaptive_load/input_variable_setter_impl.proto
  api/adaptive_load/metric_spec.proto
  api/adaptive_load/metrics_plugin_impl.proto
  api/adaptive_load/scoring_function_impl.proto
  api/adaptive_load/step_controller_impl.proto
Labels: waiting-for-review

#421 Update Envoy to c04c605a9a34139235de67f8027f257f3eec18d8
  .bazelrc
  .bazelversion
  .circleci/config.yml
  bazel/repositories.bzl
  source/client/BUILD
  source/client/benchmark_client_impl.cc
  source/client/process_impl.cc
  source/common/BUILD
  source/common/version_linkstamp.cc
  source/exe/BUILD
  test/integration/BUILD
Labels: waiting-for-changes

#417 Adaptive Load Controller headers
  include/nighthawk/adaptive_load/BUILD
  include/nighthawk/adaptive_load/adaptive_load_controller.h
  include/nighthawk/adaptive_load/input_variable_setter.h
  include/nighthawk/adaptive_load/metrics_plugin.h
  include/nighthawk/adaptive_load/scoring_function.h
  include/nighthawk/adaptive_load/step_controller.h
Labels: waiting-for-review

#424 Update Envoy to a2ebf092025e64f1b452a8bdaef13795677bceef
  bazel/repositories.bzl
  source/client/benchmark_client_impl.cc
Labels: waiting-for-review
