Repository envoyproxy/nighthawk, pull requests merged in 2021-02, with the labels that each got.

#614 Update Envoy to f6679d5 (Feb 1st 2021)
  bazel/repositories.bzl
Labels: waiting-for-review

#615 Mock Adaptive Load Controller
  test/mocks/adaptive_load/BUILD
  test/mocks/adaptive_load/mock_adaptive_load_controller.cc
  test/mocks/adaptive_load/mock_adaptive_load_controller.h
Labels: waiting-for-review

#620 CI: Fix broken docker tasks
  ci/docker/Dockerfile-nighthawk
  ci/docker/Dockerfile-nighthawk-benchmark
Labels: waiting-for-review

#621 Update Envoy to cfe0391 (Feb 5th 2021).
  .bazelrc
  .circleci/config.yml
  bazel/repositories.bzl
  source/client/output_formatter_impl.cc
  test/output_transform_main_test.cc
  test/statistic_test.cc
Labels: waiting-for-changes

#622 Documenting more details of the "Update Envoy" process.
  .bazelrc
  MAINTAINERS.md
Labels: waiting-for-review

#623 Stats: Hdr histogram serialization/deserialization
  include/nighthawk/common/BUILD
  include/nighthawk/common/statistic.h
  source/common/statistic_impl.cc
  source/common/statistic_impl.h
  test/statistic_test.cc
Labels: waiting-for-review

#616 Adaptive Load command line client
  BUILD
  api/adaptive_load/BUILD
  source/adaptive_load/BUILD
  source/adaptive_load/adaptive_load_client_main.cc
  source/adaptive_load/adaptive_load_client_main.h
  source/exe/BUILD
  source/exe/adaptive_load_client_main_entry.cc
  test/adaptive_load/BUILD
  test/adaptive_load/adaptive_load_client_main_test.cc
  test/adaptive_load/test_data/golden_output.textproto
  test/adaptive_load/test_data/invalid_session_spec.textproto
  test/adaptive_load/test_data/valid_session_spec.textproto
Labels: waiting-for-review

#628 Fix potential hangs on exit & cap drain wait time
  ci/do_ci.sh
  source/client/benchmark_client_impl.cc
  source/client/benchmark_client_impl.h
  test/benchmark_http_client_test.cc
  test/integration/configurations/nighthawk_https_origin.yaml
  test/integration/test_integration_basics.py
Labels: P0, waiting-for-review

#630 clang-tidy: address complaints
  source/adaptive_load/adaptive_load_client_main.cc
  test/adaptive_load/adaptive_load_client_main_test.cc
Labels: waiting-for-review

#631 Update Envoy to a96ebf (Feb 16th 2021)
  bazel/repositories.bzl
Labels: waiting-for-review

#574 Clang tidy deflaking / experiment in ci
  .circleci/config.yml
  MAINTAINERS.md
  ci/do_ci.sh
  ci/run_clang_tidy.sh
  ci/run_envoy_docker.sh
Labels: waiting-for-review

#632 Remove strict equality for error message
  test/server/http_test_server_filter_integration_test.cc
Labels: waiting-for-review

#635 Update Envoy to f9301ff (Feb 26th 2021).
  .bazelrc
  .circleci/config.yml
  bazel/repositories.bzl
  ci/do_ci.sh
  ci/run_envoy_docker.sh
  source/client/process_impl.cc
  test/output_transform_main_test.cc
Labels: waiting-for-review
