Repository envoyproxy/nighthawk, pull requests merged in 2021-08, with the labels that each got.

#716 Update Envoy to a066b5e (Aug 03th 2021)
  .bazelrc
  bazel/repositories.bzl
  source/client/benchmark_client_impl.cc
  test/benchmark_http_client_test.cc
Labels: waiting-for-review

#729 Update Envoy to e85a7f4 (Aug 10, 2021)
  bazel/repositories.bzl
  ci/run_envoy_docker.sh
Labels: waiting-for-review

#724 Decrease the amount of memory bazel uses.
  ci/do_ci.sh
Labels: waiting-for-review

#725 [QUIC 060]: Adding an e2e test that uses HTTP/3 Quic.
  extensions_build_config.bzl
  test/integration/BUILD
  test/integration/configurations/nighthawk_https_origin_quic.yaml
  test/integration/integration_test_fixtures.py
  test/integration/test_integration_basics.py
Labels: waiting-for-changes, do-not-merge, stacked-pr

#723 [QUIC 050]: Adding bootstrap generation support for HTTP/3 Quic.
  docs/root/overview.md
  extensions_build_config.bzl
  source/client/process_bootstrap.cc
  test/integration/BUILD
  test/integration/configurations/nighthawk_https_origin_quic.yaml
  test/integration/integration_test_fixtures.py
  test/integration/test_integration_basics.py
  test/process_bootstrap_test.cc
Labels: do-not-merge, stacked-pr

#722 [QUIC 040]: Migrating off deprecated fields in the bootstrap.
  docs/root/overview.md
  extensions_build_config.bzl
  source/client/process_bootstrap.cc
  test/integration/BUILD
  test/integration/configurations/nighthawk_https_origin_quic.yaml
  test/integration/integration_test_fixtures.py
  test/integration/test_integration_basics.py
  test/process_bootstrap_test.cc
Labels: do-not-merge, stacked-pr

#720 [QUIC 020]: Moving code that creates the Envoy bootstrap into its own library.
  docs/root/overview.md
  extensions_build_config.bzl
  source/client/BUILD
  source/client/process_bootstrap.cc
  source/client/process_bootstrap.h
  source/client/process_impl.cc
  source/client/process_impl.h
  test/BUILD
  test/integration/BUILD
  test/integration/configurations/nighthawk_https_origin_quic.yaml
  test/integration/integration_test_fixtures.py
  test/integration/test_integration_basics.py
  test/process_bootstrap_test.cc
  test/test_common/BUILD
  test/test_common/proto_matchers.cc
  test/test_common/proto_matchers.h
Labels: do-not-merge, stacked-pr

#731 Simplifying calculation of connections for Fortio.
  source/client/output_formatter_impl.cc
  test/output_formatter_test.cc
Labels: waiting-for-review

#732 Adding missing dependencies for process_bootstrap_test.
  test/BUILD
Labels: waiting-for-review

#734 Update Envoy to 95038fe (Aug 12th 2021).
  bazel/repositories.bzl
  source/client/client.cc
  source/client/process_bootstrap.cc
  source/client/process_bootstrap.h
  source/client/process_impl.cc
  source/client/process_impl.h
  source/client/service_impl.cc
  test/process_bootstrap_test.cc
  test/process_test.cc
  test/service_test.cc
Labels: waiting-for-review

#736 Update Envoy to dee7021 (Aug 18th 2021).
  bazel/repositories.bzl
  ci/do_ci.sh
  include/nighthawk/common/request_source.h
  source/client/client_worker_impl.cc
  source/common/request_source_impl.cc
  source/common/request_source_impl.h
  source/request_source/request_options_list_plugin_impl.cc
  source/request_source/request_options_list_plugin_impl.h
  test/client_worker_test.cc
  test/mocks/common/mock_request_source.h
  test/request_source/stub_plugin_impl.cc
  test/request_source/stub_plugin_impl.h
Labels: waiting-for-review

#740 Update Envoy to 74d5ef8 (Aug 30th 2021).
  bazel/repositories.bzl
  source/client/stream_decoder.h
  source/request_source/request_options_list_plugin_impl.cc
  source/server/README.md
  test/integration/configurations/nighthawk_http_origin.yaml
  test/integration/configurations/nighthawk_https_origin.yaml
  test/integration/configurations/nighthawk_track_timings.yaml
  test/integration/configurations/sni_origin.yaml
  test/options_test.cc
  test/request_source/request_source_plugin_test.cc
  test/test_common/BUILD
  test/test_common/proto_matchers.cc
  test/test_common/proto_matchers.h
Labels: waiting-for-review

#741 Noting that documentation update should be done on every Envoy update.
  MAINTAINERS.md
Labels: waiting-for-review
