Repository envoyproxy/nighthawk, pull requests merged in 2022-04, with the labels that each got.

#825 Adding the test step into AZP
  .azure-pipelines/bazel.yml
  .azure-pipelines/pipelines.yml
  ci/do_ci.sh
Labels: waiting-for-review

#828 Update envoy to 90fb3c8 (2022-04-11)
  .bazelversion
  bazel/repositories.bzl
  test/BUILD
  test/integration/configurations/nighthawk_http_origin.yaml
  test/integration/configurations/nighthawk_https_origin.yaml
  test/integration/configurations/nighthawk_https_origin_quic.yaml
  test/integration/configurations/nighthawk_track_timings.yaml
  test/integration/configurations/sni_origin.yaml
  test/process_test.cc
Labels: waiting-for-ci

#827 Adding all our CI jobs to AZP.
  .azure-pipelines/pipelines.yml
  ci/do_ci.sh
  ci/run_clang_tidy.sh
  test/BUILD
Labels: waiting-for-review

#831 Update envoy to 03efacf (04/11/2022)
  bazel/repositories.bzl
Labels: waiting-for-review

#834 Update Envoy to 569f239 (Apr 18th 2022).
  .bazelrc
  bazel/repositories.bzl
  test/integration/test_integration_basics.py
Labels: waiting-for-review

#835 Adopt Envoy's formatting in tools/gen_compilation_database.py.
  tools/format_python_tools.py
  tools/gen_compilation_database.py
Labels: waiting-for-review

#836 Migrate our docker workflow to AZP.
  .azure-pipelines/bazel.yml
  .azure-pipelines/pipelines.yml
  MAINTAINERS.md
  ci/do_ci.sh
  ci/docker/benchmark_azp_push.sh
  ci/docker/docker_azp_push.sh
  ci/run_envoy_docker.sh
Labels: waiting-for-review

#838 Updating instructions on how to build Nighthawk.
  README.md
Labels: waiting-for-review

#841 Update Envoy to bf675a8 (Apr 25th 2022)
  MAINTAINERS.md
  bazel/repositories.bzl
  source/client/benchmark_client_impl.h
  source/client/client_worker_impl.h
  source/common/sequencer_impl.h
  source/common/statistic_impl.cc
Labels: waiting-for-ci

#843 Disable integration tests that cannot execute locally.
  ci/do_ci.sh
  test/integration/test_integration_basics.py
  test/integration/utility.py
Labels: waiting-for-review

#844 repokitteh: implement /retest on AZP
  repokitteh.star
Labels: rk:blessed
