Repository envoyproxy/nighthawk, pull requests merged in 2022-11, with the labels that each got.

#930 Add user defined outputs to the nighthawk::Result.
  api/client/output.proto
  include/nighthawk/client/output_collector.h
  source/client/output_collector_impl.cc
  source/client/output_collector_impl.h
  source/client/process_impl.cc
  test/BUILD
  test/output_collector_test.cc
  test/output_formatter_test.cc
Labels: waiting-for-review

#936 Update Envoy to 6b7c95d.
  MAINTAINERS.md
  WORKSPACE
  bazel/repositories.bzl
  ci/do_ci.sh
  requirements.txt
Labels: waiting-for-review

#938 Log and re-throw on NigthhawkException same as on EnvoyException.
  source/client/process_impl.cc
Labels: waiting-for-review

#931 Create plugin that logs headers according to configuration.
  api/user_defined_output/BUILD
  api/user_defined_output/log_response_headers.proto
  source/user_defined_output/BUILD
  source/user_defined_output/log_response_headers_plugin.cc
  source/user_defined_output/log_response_headers_plugin.h
  test/user_defined_output/BUILD
  test/user_defined_output/log_response_headers_plugin_test.cc
Labels: waiting-for-review, waiting-for-ci

#942 Change signature for createUserDefinedOutputPlugin to allow validation and prevent unnecessary casting
  ci/do_ci.sh
  include/nighthawk/user_defined_output/user_defined_output_plugin.h
  source/client/process_impl.cc
  source/user_defined_output/log_response_headers_plugin.cc
  source/user_defined_output/log_response_headers_plugin.h
  source/user_defined_output/user_defined_output_plugin_creator.cc
  source/user_defined_output/user_defined_output_plugin_creator.h
  test/benchmark_http_client_test.cc
  test/user_defined_output/fake_plugin/fake_user_defined_output.cc
  test/user_defined_output/fake_plugin/fake_user_defined_output.h
  test/user_defined_output/fake_plugin/fake_user_defined_output_test.cc
  test/user_defined_output/log_response_headers_plugin_test.cc
  test/user_defined_output/user_defined_output_plugin_creator_test.cc
Labels: waiting-for-review

#943 Update Envoy to d79d554 (Nov 14th 2022)
  bazel/repositories.bzl
  extensions_build_config.bzl
  requirements.txt
  source/client/process_impl.cc
  tools/code_format/config.yaml
Labels: waiting-for-ci

#945 Upload coverage report as a pipeline artifact.
  .azure-pipelines/pipelines.yml
  test/run_nighthawk_bazel_coverage.sh
Labels: waiting-for-review

#947 Update Envoy to e34e8b7 (Nov 28th 2022)
  .bazelrc
  .bazelversion
  bazel/repositories.bzl
  ci/run_envoy_docker.sh
Labels: waiting-for-review

#949 Change User Defined Output proto to have optional error status
  api/client/output.proto
  source/client/benchmark_client_impl.cc
  source/client/benchmark_client_impl.h
  test/benchmark_http_client_test.cc
Labels: waiting-for-review
