Repository envoyproxy/nighthawk, pull requests merged in 2022-08, with the labels that each got.

#882 Update Envoy to 0d510b8 (Aug 01, 2022)
  .bazelrc
  bazel/repositories.bzl
Labels: waiting-for-review

#883 Update python dependencies to their latest version.
  requirements.txt
Labels: waiting-for-review

#884 Create documentation for finding major dependency updates
  MAINTAINERS.md
  requirements.txt
Labels: waiting-for-review

#886 Remove --assert=plain workaround in pytest
  benchmarks/benchmarks.py
  test/integration/integration_test.py
  test/integration/unit_tests/test_nighthawk_test_server.py
  test/integration/unit_tests/test_utility.py
Labels: waiting-for-review

#887 Use proto matcher instead of debug_string matching for protos.
  test/BUILD
  test/options_test.cc
Labels: waiting-for-review

#890 Remove all instances of using DebugString in tests to compare protos
  test/adaptive_load/BUILD
  test/adaptive_load/adaptive_load_controller_test.cc
  test/adaptive_load/fake_plugins/fake_input_variable_setter/BUILD
  test/adaptive_load/fake_plugins/fake_input_variable_setter/fake_input_variable_setter_test.cc
  test/adaptive_load/fake_plugins/fake_metrics_plugin/BUILD
  test/adaptive_load/fake_plugins/fake_metrics_plugin/fake_metrics_plugin_test.cc
  test/adaptive_load/fake_plugins/fake_step_controller/BUILD
  test/adaptive_load/fake_plugins/fake_step_controller/fake_step_controller_test.cc
  test/adaptive_load/input_variable_setter_test.cc
  test/adaptive_load/metrics_evaluator_test.cc
  test/adaptive_load/scoring_function_test.cc
  test/adaptive_load/step_controller_test.cc
  test/common/BUILD
  test/common/nighthawk_service_client_test.cc
  test/distributor/BUILD
  test/distributor/nighthawk_distributor_client_test.cc
  test/request_source/BUILD
  test/request_source/request_source_plugin_test.cc
  test/sink/BUILD
  test/sink/nighthawk_sink_client_test.cc
  test/sink/sink_service_test.cc
Labels: waiting-for-review

#885 Add new GetMetricByNameWithReportingPeriod function
  include/nighthawk/adaptive_load/BUILD
  include/nighthawk/adaptive_load/metrics_evaluator.h
  include/nighthawk/adaptive_load/metrics_plugin.cc
  include/nighthawk/adaptive_load/metrics_plugin.h
  source/adaptive_load/metrics_evaluator_impl.cc
  source/adaptive_load/metrics_evaluator_impl.h
  test/adaptive_load/fake_plugins/fake_metrics_plugin/fake_metrics_plugin.cc
  test/adaptive_load/fake_plugins/fake_metrics_plugin/fake_metrics_plugin.h
  test/adaptive_load/metrics_evaluator_test.cc
  test/adaptive_load/metrics_plugin_test.cc
  test/mocks/adaptive_load/mock_metrics_evaluator.h
Labels: waiting-for-ci

#893 Update Envoy to aab8ef5 (Aug 09 2022).
  .bazelrc
  .bazelversion
  MAINTAINERS.md
  bazel/repositories.bzl
  tools/code_format/config.yaml
  tools/gen_compilation_database.py
Labels: waiting-for-review

#894 Refactor subprocess mixin to control setting up and tearing down chil…
  test/integration/BUILD
  test/integration/nighthawk_test_server.py
  test/integration/subprocess_mixin.py
  test/integration/unit_tests/BUILD
  test/integration/unit_tests/test_subprocess_mixin.py
Labels: waiting-for-changes

#896 Relax expectations of INVALID_ARGUMENT errors for protobufs.
  test/options_test.cc
Labels: waiting-for-ci

#899 Update Envoy to c2fccb2 (Aug 22nd 2022)
  bazel/repositories.bzl
  test/adaptive_load/BUILD
  test/common/BUILD
  test/common/nighthawk_service_client_test.cc
  test/distributor/BUILD
  test/distributor/nighthawk_distributor_client_test.cc
  test/sink/BUILD
  test/sink/nighthawk_sink_client_test.cc
  test/test_common/BUILD
  test/test_common/mock_stream.h
Labels: waiting-for-review

#901 Add test fixture support for backend test server with multiple listener ports
  test/integration/configurations/nighthawk_5_listeners_http_origin.yaml
  test/integration/integration_test_fixtures.py
  test/integration/nighthawk_test_server.py
  test/integration/test_integration_basics.py
Labels: waiting-for-review

#898 Add base CDS churn component and test.
  api/configuration/BUILD
  api/configuration/README.md
  api/configuration/cluster_config_manager.proto
  benchmarks/BUILD
  benchmarks/README.md
  benchmarks/configurations/dynamic_resources.yaml
  benchmarks/configurations/lds.yaml
  benchmarks/dynamic_benchmarks.py
  benchmarks/dynamic_config_envoy_proxy.py
  benchmarks/dynamic_test/test_cds_churn_with_traffic.py
  benchmarks/envoy_proxy.py
  benchmarks/run_benchmark.sh
  benchmarks/static_benchmarks.py
  benchmarks/templates/simple_plot.html
  benchmarks/test/test_discovery.py
  benchmarks/utilities.py
  dynamic_config/BUILD
  dynamic_config/README.md
  dynamic_config/dynamic_config_manager.py
  dynamic_config/dynamic_config_manager_test.py
  dynamic_config/dynamic_config_server.py
  requirements.txt
  test/integration/BUILD
  test/integration/nighthawk_test_server.py
Labels: waiting-for-changes

#903 Update Envoy to 5183dbf (Aug 26th 2021)
  .bazelrc
  api/client/BUILD
  api/distributor/BUILD
  api/request_source/BUILD
  api/sink/BUILD
  bazel/repositories.bzl
Labels: waiting-for-review
